//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiTablePro.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiTablePro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mtp_logo_128 {
            get {
                object obj = ResourceManager.GetObject("mtp_logo_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Slots&quot;:[{&quot;Priority&quot;:0,&quot;ActivityUse&quot;:1,&quot;X&quot;:-10,&quot;Y&quot;:0,&quot;Width&quot;:960,&quot;Height&quot;:694,&quot;CanStack&quot;:false},{&quot;Priority&quot;:0,&quot;ActivityUse&quot;:1,&quot;X&quot;:950,&quot;Y&quot;:0,&quot;Width&quot;:960,&quot;Height&quot;:694,&quot;CanStack&quot;:false},{&quot;Priority&quot;:0,&quot;ActivityUse&quot;:0,&quot;X&quot;:-10,&quot;Y&quot;:690,&quot;Width&quot;:485,&quot;Height&quot;:366,&quot;CanStack&quot;:true},{&quot;Priority&quot;:0,&quot;ActivityUse&quot;:0,&quot;X&quot;:465,&quot;Y&quot;:690,&quot;Width&quot;:485,&quot;Height&quot;:366,&quot;CanStack&quot;:true},{&quot;Priority&quot;:0,&quot;ActivityUse&quot;:0,&quot;X&quot;:950,&quot;Y&quot;:690,&quot;Width&quot;:485,&quot;Height&quot;:366,&quot;CanStack&quot;:true},{&quot;Priority&quot;:0,&quot;ActivityUse&quot;:0,&quot;X&quot;:1425,&quot;Y&quot;:690,&quot;Width&quot;:485,&quot;Heig [rest of string was truncated]&quot;;.
        /// </summary>
        public static string profileDefault1920x1080 {
            get {
                return ResourceManager.GetString("profileDefault1920x1080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Slots&quot;:[{&quot;Priority&quot;:0,&quot;ActivityUse&quot;:1,&quot;X&quot;:0,&quot;Y&quot;:0,&quot;Width&quot;:485,&quot;Height&quot;:366,&quot;CanStack&quot;:false},{&quot;Priority&quot;:0,&quot;ActivityUse&quot;:0,&quot;X&quot;:485,&quot;Y&quot;:0,&quot;Width&quot;:485,&quot;Height&quot;:366,&quot;CanStack&quot;:true}]}.
        /// </summary>
        public static string profileEmpty {
            get {
                return ResourceManager.GetString("profileEmpty", resourceCulture);
            }
        }
    }
}
