//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterPokerTableManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BetterPokerTableManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Slots&quot;:[{&quot;Id&quot;:0,&quot;ActivityUse&quot;:1,&quot;Status&quot;:0,&quot;X&quot;:-10,&quot;Y&quot;:0,&quot;Width&quot;:955,&quot;Height&quot;:691},{&quot;Id&quot;:0,&quot;ActivityUse&quot;:1,&quot;Status&quot;:0,&quot;X&quot;:930,&quot;Y&quot;:0,&quot;Width&quot;:955,&quot;Height&quot;:691},{&quot;Id&quot;:0,&quot;ActivityUse&quot;:0,&quot;Status&quot;:0,&quot;X&quot;:-8,&quot;Y&quot;:682,&quot;Width&quot;:485,&quot;Height&quot;:366},{&quot;Id&quot;:0,&quot;ActivityUse&quot;:0,&quot;Status&quot;:0,&quot;X&quot;:461,&quot;Y&quot;:682,&quot;Width&quot;:485,&quot;Height&quot;:366},{&quot;Id&quot;:0,&quot;ActivityUse&quot;:0,&quot;Status&quot;:0,&quot;X&quot;:930,&quot;Y&quot;:682,&quot;Width&quot;:485,&quot;Height&quot;:366},{&quot;Id&quot;:0,&quot;ActivityUse&quot;:0,&quot;Status&quot;:0,&quot;X&quot;:1400,&quot;Y&quot;:683,&quot;Width&quot;:485,&quot;Height&quot;:366}]}.
        /// </summary>
        internal static string configDefault1920x1080 {
            get {
                return ResourceManager.GetString("configDefault1920x1080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Slots&quot;:[{&quot;Id&quot;:0,&quot;ActivityUse&quot;:1,&quot;Status&quot;:0,&quot;X&quot;:0,&quot;Y&quot;:0,&quot;Width&quot;:485,&quot;Height&quot;:366},{&quot;Id&quot;:0,&quot;ActivityUse&quot;:0,&quot;Status&quot;:0,&quot;X&quot;:485,&quot;Y&quot;:0,&quot;Width&quot;:485,&quot;Height&quot;:366}]}.
        /// </summary>
        internal static string configEmpty {
            get {
                return ResourceManager.GetString("configEmpty", resourceCulture);
            }
        }
    }
}
